spring.application.name=back

# tentando atalizar o propperties
spring.datasource.url=${DATABASE_DEV_URL}?useSSL=false
spring.datasource.username=${DATABASE_DEV_USER_NAME}
spring.datasource.password=${DATABASE_DEV_PASSWORD}
spring.datasource.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
api.security.token.secret=${SECRET_KEY}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_DEV_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_DEV_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${SERVER_DEV_URL:http://localhost:8080/auth/google/callback}

# Server Configuration
server.url=http://localhost:8080
frontend.url=http://localhost:5173

#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa